# Generated by Django 4.2 on 2023-04-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('C', 'Clothing'), ('S', 'Shoes'), ('A', 'Acessories')], max_length=10),
        ),
    ]
