# Generated by Django 4.2 on 2023-04-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0002_alter_items_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='clothing_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')]),
        ),
        migrations.AlterField(
            model_name='items',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('N', 'Neutral')]),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Acessories', 'Acessories')]),
        ),
    ]
