# Generated by Django 4.2 on 2023-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0003_items_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
