# Generated by Django 4.2 on 2023-04-18 01:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0004_alter_items_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='shoe_size',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
    ]
