# Generated by Django 4.2 on 2023-04-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0007_alter_items_clothing_size_alter_items_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.CharField(blank=True, choices=[('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories')]),
        ),
    ]
