# Generated by Django 4.2 on 2023-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0008_alter_items_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tags',
            field=models.CharField(),
        ),
    ]
